kind: pipeline
type: docker
name: default
trigger:
  event:
    - pull_request
    - push
    - custom
steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      registry: harbor.pivotstudio.cn
      repo: harbor.pivotstudio.cn/pivot-lang/runner
      tags:
        - latest
        - build-${DRONE_BUILD_NUMBER}
    when:
      branch:
        - main
      event:
        - push

  - name: k8s cd
    image: harbor.pivotstudio.cn/common/dron8s:latest
    pull: if-not-exists
    depends_on:
      - "docker"
    settings:
      yaml: deploy/hustcats-backend.yaml
      build_tag: build-${DRONE_BUILD_NUMBER}
      kubeconfig:
        from_secret: kube_config
    when:
      branch:
        - main
      event:
        - push